name: Android Master CI

on:
  push:
    branches:
      - v0.x

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 10

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Sign EPD APK
        uses: r0adkll/sign-android-release@v1
        id: sign-epd
        with:
          releaseDirectory: app/build/outputs/apk/epd/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign Home APK
        uses: r0adkll/sign-android-release@v1
        id: sign-home
        with:
          releaseDirectory: app/build/outputs/apk/home/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload EPD APK
        uses: actions/upload-artifact@v2
        with:
          name: e-ink-launcher-epd-release
          path: ${{ steps.sign-epd.outputs.signedReleaseFile }}

      - name: Upload Home APK
        uses: actions/upload-artifact@v2
        with:
          name: e-ink-launcher-home-release
          path: ${{ steps.sign-home.outputs.signedReleaseFile }}
