name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - v0.x
  push:
    branches:
      - v0.x

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 10

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Upload EPD APK
        uses: actions/upload-artifact@v2
        with:
          name: e-ink-launcher-epd-release
          path: |
            app/build/outputs/apk/epd/release/app-epd-release-unsigned.apk
            app/build/outputs/apk/home/release/app-home-release-unsigned.apk
